/**
 * AISpur brand mark — "Velocity Crest".
 *
 * Two interlocking wings read as forward motion; the centre node is the AI
 * core. Drawn inline rather than loaded as a file so it inherits `currentColor`
 * for the wordmark side and stays crisp at any size (the tray icon ships as a
 * separate PNG set generated by `scripts/generate-icons.swift`).
 */
export interface BrandLogoProps {
  /** Rendered edge length in px. */
  size?: number;
  className?: string;
}

export function BrandLogo({ size = 22, className }: BrandLogoProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      className={className}
      role="img"
      aria-label="AISpur"
    >
      <rect x="0" y="0" width="100" height="100" rx="22" fill="var(--brand-900, #1C1C1E)" />
      {/* Upper wing */}
      <path d="M 50 14 L 80 48 L 56 50 L 50 24 Z" fill="var(--brand-400, #E8700C)" />
      {/* Lower wing */}
      <path d="M 50 86 L 20 52 L 44 50 L 50 76 Z" fill="var(--brand-300, #FF6A33)" />
      {/* Left fold — depth */}
      <path d="M 50 14 L 20 52 L 44 50 L 50 36 Z" fill="#1C1C1E" opacity="0.35" />
      {/* Right fold — highlight */}
      <path d="M 50 86 L 80 48 L 56 50 L 50 64 Z" fill="#FF8C5A" opacity="0.35" />
      {/* AI node */}
      <circle cx="50" cy="50" r="5.5" fill="#FFFFFF" />
    </svg>
  );
}
